wp <- read.csv("water_potability.csv")
summary(wp)
str(wp)
wp <- na.omit(wp)
str(wp)
wp <- scale(wp)
head(wp, n=3)
install.packages("caret")
library(caret)
install.packages("e1071")
library(e1071)
set.seed(123)
wp <- as.data.frame(wp)
colnames(wp) <- c("ph", "Hardness", "Solids", "Chloramines", "Sulfate", "Conductivity", "Organic_carbon", "Trihalomethanes", "Turbidity", "Potability")
str(wp)
index <- createDataPartition(wp$Potability, p = 0.8, list = FALSE)
train_data <- wp[index, ]
test_data <- wp[-index, ]
nb_model <- naiveBayes(Potability ~ ., data = train_data)
predictions <- predict(nb_model, newdata = test_data)
conf_matrix <- table(predictions, test_data$Potability)
print(conf_matrix)
set.seed(123)
nnb_model <- naiveBayes(Potability ~ ., data = wp)
nnb_model
conf_matrix <- table(predictions, test_data$Potability)
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
precision <- conf_matrix[2, 2] / sum(conf_matrix[, 2])
recall <- conf_matrix[2, 2] / sum(conf_matrix[2, ])
f1_score <- 2 * (precision * recall) / (precision + recall)
print(conf_matrix)
cat("Accuracy:", accuracy, "\n")
cat("Precision:", precision, "\n")
cat("Recall:", recall, "\n")
cat("F1-Score:", f1_score, "\n")

