install.packages("rpart")
install.packages("rpart.plot")
install.packages("caret")
library(rpart)
library(rpart.plot)
library(caret)
data <- read.csv("water_potability.csv")
head(data, 10)
data <- na.omit(data)
head(data, 10)
set.seed(123)
train_indices <- createDataPartition(data$Potability, p = 0.8, list = FALSE)
train_data <- data[train_indices, ]
test_data <- data[-train_indices, ]
model <- rpart(Potability ~ ph + Hardness + Solids + Chloramines + Sulfate + Conductivity + Organic_carbon + Trihalomethanes + Turbidity, data = train_data, method = "class")
rpart.plot(model, main = "Decision Tree for Water Potability", extra = 1)
printcp(model)
confusionMatrix - table(predictions, test_data$Potability)
cm - confusionMatrix(table(predictions, test_data$Potability))
print(cm)
print(paste(Accuracy , cm$overall[Accuracy]))
predictions - predict(model, newdata = test_data, type = class)
conf_matrix - confusionMatrix(predictions, test_data$Potability)
conf_matrix - confusionMatrix(table(predictions, test_data$Potability))
print(conf_matrix)
